In [5]:
#!/usr/bin/env python
# coding: utf-8

# In[ ]:


import sqlite3

try:
    db = sqlite3.connect('ebookstore_db1') #make the database
    cursor = db.cursor() 
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS books1(id INTEGER PRIMARY KEY, Title TEXT, Author Text, Qty INTEGER)
    ''') #make a table called books1 in the database with columns id as primary key, title, author, and quantity
    db.commit()
except Exception as e: #if anything goes wrong, put it back to the previous version
    db.rollback()
    raise e



# In[18]:


#input the entries for table books1
my_books = [(3001, 'A Tale of Two Cities', 'Charles Dickens', 30), (3002, "Harry Potter and the Philosopher's Stone", 'J.K. Rowling', 40), (3003, 'The Lion, the Witch and the Wardrobe', 'C.S. Lewis', 25), (3004, 'The Lord of the Rings', 'J.R.R. Tolkien', 37), (3005, 'Alice in Wonderland', 'Lewis Carroll', 12)]

cursor.executemany('''INSERT INTO books1(id, Title, Author, Qty) VALUES(?,?,?,?)''',my_books)

db.commit()



# In[22]:


books1_list = [] 
cursor.execute("SELECT * FROM books1") #select all the books in the database
for row in cursor: #for each row
    books1_list.append(row[0]) #append all the items (in id row) in the list 
#print(books1_list) 
    
userinput1 = ""
while userinput1 != '0':#ask what user wants to do in a while loop
    userinput1 = input('Select a number:\n1. Enter book \n2. Update book \n3. Delete book \n4. Search books \n0. Exit:> ')
    if userinput1 == '1': #if user selects 1, ask for prompts
        userinput2 = input('Which book would you like to add?')
        userinput3 = input('Who is the author of this book')
        userinput4 = input('What is the quantity of this book?')
        Title = userinput2 #assign userinputs to necessary variables
        Author = userinput3
        Qty = userinput4
        cursor.execute('''INSERT INTO books1 (Title, Author, Qty) VALUES (?,?,?)''', (Title, Author, Qty)) #insert these values from userinput to the table called books1
        print('Book added to database.')
        db.commit()
    elif userinput1 == '2':
        cursor.execute("SELECT * FROM books1") #show all the books in the database
        for row in cursor:
            print('{0} : {1} by {2} with a quantity of {3}'.format(row[0], row[1], row[2], row[3])) #print using this format
            books1_list.append(row[0])
        userinput5 = int(input('Which book do you want to update? type the id of the book you wish to update.'))
        if userinput5 in books1_list: 
            userinput6 = input(f'Which information do you want to update on book {userinput5}? \n1. Title \n2. Author \n3.Qty') #ask user what info they want to update
            if userinput6 == '1':#if user chooses 1 ask for new title
                userinput7 = input('What title do you want to change it to?')
                Title = userinput7 #assign userinputs to necessary variables
                id = userinput5
                cursor.execute('''UPDATE books1 SET Title = ? WHERE id = ?''', (Title, id))
                db.commit()
                print('Title updated')
            elif userinput6 == '2': #if user chooses 2 ask for new author name
                userinput8 = input('What is the new author name?')
                Author = userinput8 #assign userinputs to necessary variables
                id = userinput5
                cursor.execute('''UPDATE books1 SET Author = ? WHERE id = ?''', (Author, id))
                db.commit()
                print('Author name updated')
            elif userinput6 == '3': #if user chooses 3 ask for new quantity
                userinput9 = input(f'What is the new quantity of book {userinput5}?')
                Qty = userinput9 #assign userinputs to necessary variables
                id = userinput5
                cursor.execute('''UPDATE books1 SET Qty = ? WHERE id = ?''', (Qty, id)) #update the quantity of that book
                db.commit()
                print('Quantity updated')
            else: #if user enters any other thing
                print()
                print('That is not a valid input. Try again.')
                continue #go back to main menu
        else:
            print()
            print('That is not a valid input. Try again.')
            continue #back to main menu
        

    elif userinput1 == '3': #if user wants to delete something
        cursor.execute("SELECT * FROM books1") #display the contents of db
        for row in cursor:
            print('{0} : {1} by {2} with a quantity of {3}'.format(row[0], row[1], row[2], row[3])) #use this format
        
        userinput10 = int(input('Which book do you want to delete? Type the id of the book you wish to delete.'))
        if userinput10 in books1_list:
            id = userinput10 #assign userinput to id
            cursor.execute('''DELETE FROM books1 WHERE id = ? ''', (id, )) #delete the book from table books1 with that id 
            db.commit()
            print('The book is now deleted')
        else:
            print()
            print('That is not a valid input. Try again.')
            continue
    elif userinput1 == '4': #if user wants to retrieve info about a specific book
        cursor.execute("SELECT * FROM books1") #display contents of db
        for row in cursor:
            print('{0} : {1}'.format(row[0], row[1])) #in this format
        userinput11 = input('Which book do you want to search for? Type the id.') #ask which book does user want to get more info on?
        id = userinput11 #assign userinput to id variable
        cursor.execute('''SELECT Title, Author, Qty FROM books1  WHERE id = ?''', (id,)) #display everything about that book
        books1 = cursor.fetchone() 
        print(books1)
    elif userinput1 == '0': #if user wants to exit
        print('Goodbye')
        break
    else: #if user inputs anything else aside from the choices
        print()
        print('That is not a valid input. Try again.')
        continue #go back to main menu

db.commit()
db.close()


# In[ ]:





# In[ ]:

[3001, 3002, 3003, 3004, 3005]
Select a number:
1. Enter book
2. Update book
3. Delete book
4. Search books
0. Exit:> 1
Which book would you like to add?ice fire
Who is the author of this bookgeorge martin
What is the quantity of this book?4
Book added to database.
Select a number:
1. Enter book
2. Update book
3. Delete book
4. Search books
0. Exit:> 2
3001 : A Tale of Two Cities by Charles Dickens with a quantity of 30
3002 : Harry Potter and the Philosopher's Stone by J.K. Rowling with a quantity of 40
3003 : The Lion, the Witch and the Wardrobe by C.S. Lewis with a quantity of 25
3004 : The Lord of the Rings by J.R.R. Tolkien with a quantity of 37
3005 : Alice in Wonderland by Lewis Carroll with a quantity of 12
3006 : ice fire by george martin with a quantity of 4
Which book do you want to update? type the id of the book you wish to update.3006
Which information do you want to update on book 3006?
1. Title
2. Author
3.Qty1
What title do you want to change it to?Ice and Fire
Title updated
Select a number:
1. Enter book
2. Update book
3. Delete book
4. Search books
0. Exit:> 2
3001 : A Tale of Two Cities by Charles Dickens with a quantity of 30
3002 : Harry Potter and the Philosopher's Stone by J.K. Rowling with a quantity of 40
3003 : The Lion, the Witch and the Wardrobe by C.S. Lewis with a quantity of 25
3004 : The Lord of the Rings by J.R.R. Tolkien with a quantity of 37
3005 : Alice in Wonderland by Lewis Carroll with a quantity of 12
3006 : Ice and Fire by george martin with a quantity of 4
Which book do you want to update? type the id of the book you wish to update.3006
Which information do you want to update on book 3006?
1. Title
2. Author
3.Qty2
What is the new author name?Martin G.
Author name updated
Select a number:
1. Enter book
2. Update book
3. Delete book
4. Search books
0. Exit:> 4
3001 : A Tale of Two Cities
3002 : Harry Potter and the Philosopher's Stone
3003 : The Lion, the Witch and the Wardrobe
3004 : The Lord of the Rings
3005 : Alice in Wonderland
3006 : Ice and Fire
Which book do you want to search for? Type the id.3006
('Ice and Fire', 'Martin G.', 4)
Select a number:
1. Enter book
2. Update book
3. Delete book
4. Search books
0. Exit:> 3
3001 : A Tale of Two Cities by Charles Dickens with a quantity of 30
3002 : Harry Potter and the Philosopher's Stone by J.K. Rowling with a quantity of 40
3003 : The Lion, the Witch and the Wardrobe by C.S. Lewis with a quantity of 25
3004 : The Lord of the Rings by J.R.R. Tolkien with a quantity of 37
3005 : Alice in Wonderland by Lewis Carroll with a quantity of 12
3006 : Ice and Fire by Martin G. with a quantity of 4
Which book do you want to delete? Type the id of the book you wish to delete.3006
The book is now deleted
Select a number:
1. Enter book
2. Update book
3. Delete book
4. Search books
0. Exit:> 4
3001 : A Tale of Two Cities
3002 : Harry Potter and the Philosopher's Stone
3003 : The Lion, the Witch and the Wardrobe
3004 : The Lord of the Rings
3005 : Alice in Wonderland

KeyboardInterrupt: Interrupted by user